export const GET_QUESTIONS_INIT = "GET_QUESTIONS_INIT";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAILED = "GET_QUESTIONS_FAILED";

export const GET_DOCUMENTS_INIT = "GET_DOCUMENTS_INIT";
export const GET_DOCUMENTS_SUCCESS = "GET_DOCUMENTS_SUCCESS";
export const GET_DOCUMENTS_FAILED = "GET_DOCUMENTS_FAILED";

export const GET_BANKS_INIT = "GET_BANKS_INIT";
export const GET_BANKS_SUCCESS = "GET_BANKS_SUCCESS";
export const GET_BANKS_FAILED = "GET_BANKS_FAILED";

export const GET_SCHEDULE_INIT = "GET_SCHEDULE_INIT";
export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS";
export const GET_SCHEDULE_FAILED = "GET_SCHEDULE_FAILED";

export const GET_CURRENCIES_INIT = "GET_CURRENCIES_INIT";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_FAILED = "GET_CURRENCIES_FAILED";

export const SET_AUTH_COMPONENT = "SET_AUTH_COMPONENT";

export const REGISTER_INIT = "REGISTER_INIT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const SET_GOOGLE_REGISTRATION = "SET_GOOGLE_REGISTRATION";

export const SENT_PASSWORD_EMAIL_INIT = "SENT_PASSWORD_EMAIL_INIT";
export const SENT_PASSWORD_EMAIL_SUCCESS = "SENT_PASSWORD_EMAIL_SUCCESS";
export const SENT_PASSWORD_EMAIL_FAILED = "SENT_PASSWORD_EMAIL_FAILED";

export const VALIDATE_PASSWORD_CHANGE_INIT = "VALIDATE_PASSWORD_CHANGE_INIT";
export const VALIDATE_PASSWORD_CHANGE_SUCCESS = "VALIDATE_PASSWORD_CHANGE_SUCCESS";
export const VALIDATE_PASSWORD_CHANGE_FAILED = "VALIDATE_PASSWORD_CHANGE_FAILED";

export const CHANGE_PASSWORD_INIT = "CHANGE_PASSWORD_INIT";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

export const CHANGE_PHONE_INIT = "CHANGE_PHONE_INIT";
export const CHANGE_PHONE_SUCCESS = "CHANGE_PHONE_SUCCESS";
export const CHANGE_PHONE_FAILED = "CHANGE_PHONE_FAILED";

export const CHANGE_ADDRESS_INIT = "CHANGE_ADDRESS_INIT";
export const CHANGE_ADDRESS_SUCCESS = "CHANGE_ADDRESS_SUCCESS";
export const CHANGE_ADDRESS_FAILED = "CHANGE_ADDRESS_FAILED";

export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGIN_GOOGLE_INIT = "LOGIN_GOOGLE_INIT";
export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
export const LOGIN_GOOGLE_FAILED = "LOGIN_GOOGLE_FAILED";

export const GET_USER_INIT = "GET_USER_INIT";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const LOGOUT_INIT = "LOGOUT_INIT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const CHECK_AUTH_TIMEOUT = "CHECK_AUTH_TIMEOUT";

export const UPDATE_PROFILE_INIT = "UPDATE_PROFILE_INIT";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const SHOW_QUESTIONS_MODAL = "SHOW_QUESTIONS_MODAL";
export const HIDE_QUESTIONS_MODAL = "HIDE_QUESTIONS_MODAL";

export const GET_ACCOUNTS_INIT = "GET_ACCOUNTS_INIT";
export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS";
export const GET_ACCOUNTS_ERROR = "GET_ACCOUNTS_ERROR";

export const GET_ACCOUNT_DETAILS_INIT = "GET_ACCOUNT_DETAILS_INIT";
export const GET_ACCOUNT_DETAILS_SUCCESS = "GET_ACCOUNT_DETAILS_SUCCESS";
export const GET_ACCOUNT_DETAILS_ERROR = "GET_ACCOUNT_DETAILS_ERROR";

export const ADD_ACCOUNT_INIT = "ADD_ACCOUNT_INIT";
export const ADD_ACCOUNT_SUCCESS = "ADD_ACCOUNT_SUCCESS";
export const ADD_ACCOUNT_ERROR = "ADD_ACCOUNT_ERROR";

export const EDIT_ACCOUNT_INIT = "EDIT_ACCOUNT_INIT";
export const EDIT_ACCOUNT_SUCCESS = "EDIT_ACCOUNT_SUCCESS";
export const EDIT_ACCOUNT_ERROR = "EDIT_ACCOUNT_ERROR";

export const DELETE_ACCOUNT_INIT = "DELETE_ACCOUNT_INIT";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_ERROR = "DELETE_ACCOUNT_ERROR";

export const SET_IS_THIRD = "SET_IS_THIRD";
export const SET_CURRENCY = "SET_CURRENCY";

export const GET_EXCHANGE_DETAILS_INIT = "GET_EXCHANGE_DETAILS_INIT";
export const GET_EXCHANGE_DETAILS_SUCCESS = "GET_EXCHANGE_DETAILS_SUCCESS";

export const GET_ACTIVITY_INIT = "GET_ACTIVITY_INIT";
export const GET_ACTIVITY_SUCCESS = "GET_ACTIVITY_SUCCESS";
export const GET_ACTIVITY_ERROR = "GET_ACTIVITY_ERROR";

export const GET_EXCHANGE_PRICES_INIT = "GET_EXCHANGE_PRICES_INIT";
export const GET_EXCHANGE_PRICES_SUCCESS = "GET_EXCHANGE_PRICES_SUCCESS";
export const GET_EXCHANGE_PRICES_ERROR = "GET_EXCHANGE_PRICES_ERROR";

export const CREATE_EXCHANGE_INIT = "CREATE_EXCHANGE_INIT";
export const CREATE_EXCHANGE_SUCCESS = "CREATE_EXCHANGE_SUCCESS";
export const CREATE_EXCHANGE_FAILED = "CREATE_EXCHANGE_FAILED";

export const PROCESS_EXCHANGE_INIT = "PROCESS_EXCHANGE_INIT";
export const PROCESS_EXCHANGE_SUCCESS = "PROCESS_EXCHANGE_SUCCESS";
export const PROCESS_EXCHANGE_FAILED = "PROCESS_EXCHANGE_FAILED";

export const CANCEL_EXCHANGE_INIT = "CANCEL_EXCHANGE_INIT";
export const CANCEL_EXCHANGE_SUCCESS = "CANCEL_EXCHANGE_SUCCESS";
export const CANCEL_EXCHANGE_FAILED = "CANCEL_EXCHANGE_FAILED";

export const GET_ADVANCE_LIMITS_INIT = "GET_ADVANCE_LIMITS_INIT";
export const GET_ADVANCE_LIMITS_SUCCESS = "GET_ADVANCE_LIMITS_SUCCESS";
export const GET_ADVANCE_LIMITS_FAILED = "GET_ADVANCE_LIMITS_FAILED";

export const VALIDATE_USER_LIMIT_INIT = "VALIDATE_USER_LIMIT_INIT";
export const VALIDATE_USER_LIMIT_SUCCESS = "VALIDATE_USER_LIMIT_SUCCESS";
export const VALIDATE_USER_LIMIT_FAILED = "VALIDATE_USER_LIMIT_FAILED";

export const GET_ADVANCE_DETAILS_INIT = "GET_ADVANCE_DETAILS_INIT";
export const GET_ADVANCE_DETAILS_SUCCESS = "GET_ADVANCE_DETAILS_SUCCESS";

export const CREATE_ADVANCE_INIT = "CREATE_ADVANCE_INIT";
export const CREATE_ADVANCE_SUCCESS = "CREATE_ADVANCE_SUCCESS";
export const CREATE_ADVANCE_FAILED = "CREATE_ADVANCE_FAILED";

export const PROCESS_ADVANCE_INIT = "PROCESS_ADVANCE_INIT";
export const PROCESS_ADVANCE_SUCCESS = "PROCESS_ADVANCE_SUCCESS";
export const PROCESS_ADVANCE_FAILED = "PROCESS_ADVANCE_FAILED";

export const CANCEL_ADVANCE_INIT = "CANCEL_ADVANCE_INIT";
export const CANCEL_ADVANCE_SUCCESS = "CANCEL_ADVANCE_SUCCESS";
export const CANCEL_ADVANCE_FAILED = "CANCEL_ADVANCE_FAILED";

export const CHECK_BALANCE_INIT = "CHECK_BALANCE_INIT";
export const CHECK_BALANCE_SUCCESS = "CHECK_BALANCE_SUCCESS";
export const CHECK_BALANCE_FAILED = "CHECK_BALANCE_FAILED";

export const REMOVE_EXCHANGE_LOADING = "REMOVE_EXCHANGE_LOADING";
